name: Bazel build and tests on multiple platforms.

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/obr-builder
        with:
          platform: linux
      - name: Upload Bazel test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bazel-test-logs-linux-amd64
          path: bazel-testlogs/**/*.log

  macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/obr-builder
        with:
          platform: macos
      - name: Upload Bazel test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bazel-test-logs-macos-arm64
          path: bazel-testlogs/**/*.log

  macos-amd64:
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/obr-builder
        with:
          platform: macos
      - name: Upload Bazel test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bazel-test-logs-macos-amd64
          path: bazel-testlogs/**/*.log

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/obr-builder
        with:
          platform: windows
      - name: Upload Bazel test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bazel-test-logs-windows
          path: bazel-testlogs/**/*.log

